version: 1.0.{build}
skip_tags: true
configuration:
- Debug
- Debug_XP
- Release
- Release_XP
build_script:
- echo hello > hello.txt
- mkdir pkg
- 7z a pkg/%CONFIGURATION%.zip hello.txt
test: off
artifacts:
- path: pkg/*.zip
deploy:
  provider: GitHub
  auth_token:
    secure: Lc0feNQVBz/XlDiYdmGc3+yK8YSfFw5P0BgLYCbMnYpI+8Ng+NmMybdzKvDAPwYv
  artifact: /.*\.zip/
  draft: false
  prerelease: false
